spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST_WITH_PORT}/${DATABASE_NAME}?useSSL=true&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: pl.crystalek.budgetweb.configuration.ProdNamingStrategy

account:
  confirmation:
    email:
      config:
        return-address: https://budgetapp.pl/account-activation

password-recovery:
  email:
    config:
      return-address: https://budgetapp.pl/password-reset

change-email:
  email:
    config:
      return-address: https://budgetapp.pl/profile/change-email-confirmation