package pl.crystalek.budgetweb.filter.condition.response;

public enum SaveFilterConditionResponse {
    FILTER_NOT_EXISTS,
    FIRST_GROUP_CAN_NOT_HAVE_OPERATOR,
    GROUP_NOT_HAVE_OPERATOR_BEFORE,
    INVALID_FIELD_NAME,
    INVALID_FIRST_VALUE,
    INVALID_SECOND_VALUE,
    OPERATOR_NOT_BETWEEN_WHEN_SECOND_VALUE_SET,
    MISMATCH_OPEN_CLOSED_PARENTHESIS_NUMBER,
    UNNECESSARY_PARENTHESES,
    OPERATOR_NOT_AVAILABLE_FOR_FIELD, FIRST_CONDITION_CAN_NOT_HAVE_OPERATOR, CONDITION_NOT_HAVE_OPERATOR_BEFORE,
    SUCCESS
}
